// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPhotos = `-- name: CountPhotos :one
SELECT COUNT(*) FROM photos
WHERE event_id = $1
`

func (q *Queries) CountPhotos(ctx context.Context, eventID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPhotos, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCurrentEvent = `-- name: GetCurrentEvent :one
SELECT id, name, starts_at, ends_at, created_at, updated_at FROM events
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetCurrentEvent(ctx context.Context) (Event, error) {
	row := q.db.QueryRow(ctx, getCurrentEvent)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSingletonEvent = `-- name: UpsertSingletonEvent :one
INSERT INTO events (name, starts_at, ends_at)
VALUES ($1, $2, $3)
ON CONFLICT ((TRUE)) DO UPDATE
SET name = EXCLUDED.name,
    starts_at = EXCLUDED.starts_at,
    ends_at = EXCLUDED.ends_at,
    updated_at = now()
RETURNING id, name, starts_at, ends_at, created_at, updated_at
`

type UpsertSingletonEventParams struct {
	Name     string             `json:"name"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
}

// Keyed on the events_singleton_idx expression index, so a second boot updates
// the existing row in place instead of creating a second event.
func (q *Queries) UpsertSingletonEvent(ctx context.Context, arg UpsertSingletonEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, upsertSingletonEvent, arg.Name, arg.StartsAt, arg.EndsAt)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
