// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPhotos = `-- name: CountPhotos :one
SELECT COUNT(*) FROM photos
WHERE event_id = $1
`

func (q *Queries) CountPhotos(ctx context.Context, eventID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPhotos, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (name, starts_at, ends_at)
VALUES ($1, $2, $3)
RETURNING id, name, starts_at, ends_at, created_at, updated_at
`

type CreateEventParams struct {
	Name     string             `json:"name"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent, arg.Name, arg.StartsAt, arg.EndsAt)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentEvent = `-- name: GetCurrentEvent :one
SELECT id, name, starts_at, ends_at, created_at, updated_at FROM events
ORDER BY created_at DESC
LIMIT 1
`

// "Current" is the most recently started event; older events and their photos
// stay in the table as history once a new one is started.
func (q *Queries) GetCurrentEvent(ctx context.Context) (Event, error) {
	row := q.db.QueryRow(ctx, getCurrentEvent)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
