// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photo_queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photos (
    id, event_id, uploaded_by, client_id, storage_key, thumb_key,
    content_type, width, height, size_bytes, taken_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, event_id, uploaded_by, client_id, storage_key, thumb_key, content_type, width, height, size_bytes, taken_at, created_at
`

type CreatePhotoParams struct {
	ID          pgtype.UUID        `json:"id"`
	EventID     pgtype.UUID        `json:"event_id"`
	UploadedBy  pgtype.UUID        `json:"uploaded_by"`
	ClientID    string             `json:"client_id"`
	StorageKey  string             `json:"storage_key"`
	ThumbKey    string             `json:"thumb_key"`
	ContentType string             `json:"content_type"`
	Width       int32              `json:"width"`
	Height      int32              `json:"height"`
	SizeBytes   int64              `json:"size_bytes"`
	TakenAt     pgtype.Timestamptz `json:"taken_at"`
}

// The id is supplied by the caller rather than defaulted, because the storage
// keys (photos/{id}.jpg, thumbs/{id}.jpg) are written before the row exists.
func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, createPhoto,
		arg.ID,
		arg.EventID,
		arg.UploadedBy,
		arg.ClientID,
		arg.StorageKey,
		arg.ThumbKey,
		arg.ContentType,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.TakenAt,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UploadedBy,
		&i.ClientID,
		&i.StorageKey,
		&i.ThumbKey,
		&i.ContentType,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.TakenAt,
		&i.CreatedAt,
	)
	return i, err
}

const findPhotoByClientId = `-- name: FindPhotoByClientId :one
SELECT id, event_id, uploaded_by, client_id, storage_key, thumb_key, content_type, width, height, size_bytes, taken_at, created_at FROM photos
WHERE event_id = $1 AND client_id = $2
`

type FindPhotoByClientIdParams struct {
	EventID  pgtype.UUID `json:"event_id"`
	ClientID string      `json:"client_id"`
}

func (q *Queries) FindPhotoByClientId(ctx context.Context, arg FindPhotoByClientIdParams) (Photo, error) {
	row := q.db.QueryRow(ctx, findPhotoByClientId, arg.EventID, arg.ClientID)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UploadedBy,
		&i.ClientID,
		&i.StorageKey,
		&i.ThumbKey,
		&i.ContentType,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.TakenAt,
		&i.CreatedAt,
	)
	return i, err
}

const findPhotoById = `-- name: FindPhotoById :one
SELECT id, event_id, uploaded_by, client_id, storage_key, thumb_key, content_type, width, height, size_bytes, taken_at, created_at FROM photos
WHERE id = $1
`

func (q *Queries) FindPhotoById(ctx context.Context, id pgtype.UUID) (Photo, error) {
	row := q.db.QueryRow(ctx, findPhotoById, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UploadedBy,
		&i.ClientID,
		&i.StorageKey,
		&i.ThumbKey,
		&i.ContentType,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.TakenAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPhotosByEvent = `-- name: ListPhotosByEvent :many
SELECT id, event_id, uploaded_by, client_id, storage_key, thumb_key, content_type, width, height, size_bytes, taken_at, created_at FROM photos
WHERE event_id = $1
ORDER BY taken_at ASC, id ASC
`

// Ordered by capture time, not upload time: the offline retry queue means those
// differ, and the album should read chronologically.
func (q *Queries) ListPhotosByEvent(ctx context.Context, eventID pgtype.UUID) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listPhotosByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photo
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UploadedBy,
			&i.ClientID,
			&i.StorageKey,
			&i.ThumbKey,
			&i.ContentType,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.TakenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
