// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountPhotos(ctx context.Context, eventID pgtype.UUID) (int64, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	// The id is supplied by the caller rather than defaulted, because the storage
	// keys (photos/{id}.jpg, thumbs/{id}.jpg) are written before the row exists.
	CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindPhotoByClientId(ctx context.Context, arg FindPhotoByClientIdParams) (Photo, error)
	FindPhotoById(ctx context.Context, id pgtype.UUID) (Photo, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserById(ctx context.Context, id pgtype.UUID) (User, error)
	// "Current" is the most recently started event; older events and their photos
	// stay in the table as history once a new one is started.
	GetCurrentEvent(ctx context.Context) (Event, error)
	// Ordered by capture time, not upload time: the offline retry queue means those
	// differ, and the album should read chronologically.
	ListPhotosByEvent(ctx context.Context, eventID pgtype.UUID) ([]Photo, error)
	ListUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
